### ISSUE TITLE
Listen to when showcase dismisses

### ISSUE THREAD

**Issue by tjohnn** [erkutaras/ShowcaseView#14]
Is there a way to listen to it when user clicks on the button and the showcase is dismissed? I want to take some action on complete.

**Comment by tjohnn** [comment]
Okay I think listening to onresume in activity or fragment works for now, but it would be nice to have a non-hacky way like this

**Comment by erkutaras** [comment]
Showcase works with new Activity creation. Unfortunately, because of this, you cann't initialize any listener to listen dismisses. On the other hand, after your issue, I started to create Showcase with activityForResult with ShowcaseManager.REQUEST_CODE_SHOWCASE in new version(1.3.0) of the library. If you override onActivityResult, you can listen showcase dismisses. In my opinion, this is also hacky solution :) 

I updated readme file to listen also, thanks for your support.
